name: api-dev-codedeploy
on:
  workflow_dispatch:
  push:
    branches:
      - multi_tenant_dev

permissions:
  id-token: write 
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  codedeploy:
    name: Trigger codedeploy with latest commit to Dev Ohio
    runs-on: ubuntu-latest

    environment:
      name: DEV

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
        with:
          ref: multi_tenant_dev

      - name: Echo Branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo $branch_name
          echo "ENV name is : ${{ vars.ENV }}"

  # release_api_dev:
  #   if: github.ref == 'refs/heads/multi_tenant_dev'
  #   needs: [codedeploy]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         ref: multi_tenant_dev

  #     - name: run codedeploy-stage workflow
  #       env:
  #         GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
  #       run: |
  #         gh workflow run release-version.yml \
  #         --ref=multi_tenant_dev \
  #         --repo prashant-cloudbolt/workflow-source
