name: CSMP Stage Smoke Test Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: stage

    steps:
    - uses: actions/checkout@v4

    - name: Run CSMP V2 API Tests
      run: |
        echo "Running CSMP Stage Smoke Test Cases"
        sleep 120
        echo "job completed"