name: Build and Deploy

on:
  push:
    branches:
      - multi_tenant_stage
      - multi_tenant_dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests..."
          # Simulate a test failure
          exit 1

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK }}
        with:
          payload: |
            {
              "text": "Workflow *${{ github.workflow }}* in repository *${{ github.repository }}* has failed.",
              "attachments": [
                {
                  "color": "#ff0000",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "<${{ github.event.head_commit.url }}|${{ github.event.head_commit.id }}>",
                      "short": true
                    },
                    {
                      "title": "Commit Message",
                      "value": "${{ github.event.head_commit.message }}",
                      "short": false
                    },
                    {
                      "title": "Action Workflow",
                      "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>",
                      "short": false
                    }
                  ]
                }
              ]
            }
