###
### SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK }}
###

name: Build and Deploy
on:
  push:
    branches:
      - multi_tenant_stage
      - multi_tenant_dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          # echo "working fine"
          # Your test commands here
          exit 1  # Simulate a failure for demonstration purposes

      - name: Notify failure to Slack
        uses: act10ns/slack@v2.0.0
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK }} 
        with:
          status: ${{ job.status }}
          message: |
            :rotating_light: *Urgent*: GitHub Actions Job Failed: *${{ github.workflow }}* :rotating_light:
            Repository: ${{ github.repository }}
            Pipeline URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}