name: release-node-api-version
on:
  workflow_run:
    workflows: ["release-api-version"]
    types:
      - completed
        
permissions:
  id-token: write 
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  trigger-release-node-api-version-workflow:
    name: Trigger release node-api version workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Triggered by the completion of the first workflow on branch ${{ github.event.workflow_run.head_branch }}"

      - name: Set branch name dynamically
        id: set-branch
        run: echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Debug branch value
        run: echo "The branch is ${{ env.BRANCH }}"

      - name: run node-api release version workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run release-version.yml --repo prashant-cloudbolt/workflow-target --ref $BRANCH
