name: release-dependent-version
on:
    workflow_run:
      workflows: ["release-api-version"]
      branches:
        - multi_tenant_stage
        - multi_tenant_prod
        - multi_tenant_dev
      types:
        - completed
jobs:
  trigger-release-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - workflow-target
          - workflow-target1

    steps:
      - name: Run ${{ matrix.repository }} release version workflow
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch }}
          repo: ${{ matrix.repository }}
          owner: prashant-cloudbolt
          workflow: release-version.yml

      - name: Watch ${{ matrix.repository }} release version workflow
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          RUN_ID=${{steps.return_dispatch.outputs.run_id}}
          gh run watch $RUN_ID --repo prashant-cloudbolt/${{ matrix.repository }}