name: release-node-api-version
on:
  workflow_run:
    workflows: ["release-api-version"]
    branches:
      - multi_tenant_stage
      - multi_tenant_dev
    types:
      - completed
        
permissions:
  id-token: write 
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  trigger-release-node-api-version-workflow:
    name: Trigger release node-api version workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug branch value
        run: echo "Triggered by the completion of the first workflow on branch ${{ github.event.workflow_run.head_branch }}"

      - name: run reporting release version workflow
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch }}
          repo: workflow-target
          owner: prashant-cloudbolt
          workflow: release-version.yml

      - name: Watch reporting release version workflow
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          RUN_ID=${{steps.return_dispatch.outputs.run_id}}
          gh run watch $RUN_ID --repo prashant-cloudbolt/workflow-target
