name: Release Candidate Build
on:
  push:
    branches:
      - develop
      - main

jobs:
  content-library:
    name: Kick off content-library workflow
    uses: ./.github/workflows/content-library-release.yml
    with:
      environment: Production
      publish: true
    secrets: inherit
